### ISSUE TITLE
Default redirect_uri to protocol + host

### ISSUE THREAD

**Issue by jasonkuhrt** [jasonkuhrt/oauth2-implicit#18]
When leveraging `redirect_uri` inference we should strip off the current URI hash which is likely to not be part of the actual registered URI.

**Comment by jasonkuhrt** [comment]
@stresslimit Please review these example inferences. Do they cover our use-cases correctly?

##### Honours Protocol
```
https://foo.bar.io  --> https://foo.bar.io
http://foo.bar.io --> http://foo.bar.io
```

##### Ignores trailing slashes
```
http://foo.bar.io/ --> http://foo.bar.io
```

##### Ignores Hash
```
http://foo.bar.io#qux-wux-tux --> http://foo.bar.io
```

##### Ignores Query
```
http://foo.bar.io?qux=wux&tux=rux --> http://foo.bar.io
```

##### Ignores Path
```
http://foo.bar.io/qux/wux/tux --> http://foo.bar.io
```

**Comment by stresslimit** [comment]
Examples look good.

We should definitely have this user-configurable; there may well be a URI with path that we want to honour as `redirect_uri`. Possible options could be:

1. Strip to root URI by default, pass an arg to `use_full_redirect_uri (Bool)`
1. Use full path by default, pass an arg to `use_root_redirect_uri (Bool)`
1. Use full path by default, and pass an arg `redirect_uri (String)` where we can pass the root URI we want and lib will strip off the difference

**Comment by jasonkuhrt** [comment]
Ok great. And yeah this flexibility should be possible. We'll make sure it is.

**Comment by jasonkuhrt** [comment]
I just realized that we want `host` not `hostname`. Using `hostname` ignores the `port` which is a bad default because its likely that if the user made a request from a non-standard port they want/need the redirect to go back that same one!
