### ISSUE TITLE
Auto Serialize/Deserialize option for state

### ISSUE THREAD

**Issue by jasonkuhrt** [jasonkuhrt/oauth2-implicit#20]
We should add an option for auto serializing/deserializing objects into/out of `state`.

I'm tempted to make this feature opt-out rather than opt-in _when `state` is present_. Chances of users wanting to `Object > JSON > Serialize > Deserialize > JSON > Object` if `state` is given at all seems high to me. If they have some custom serialization goal (string literal, etc.) then they can do a bit of extra work to enable that.

@sch @stresslimit can you make some preliminary remarks about the serialization you all want to see. URLEncode, Base64, other? Pros, cons? Any browser-compatible libraries you can point to? Cheers.

**Comment by stresslimit** [comment]
Agreed on this by default. Vote for base64 just cause it will be less characters and I've seen this referenced as a strategy [in implementations using google oauth].

**Comment by jasonkuhrt** [comment]
> Vote for base64 just cause it will be less characters and I've seen this referenced as a strategy [in implementations using google oauth].

Great thanks, I'll go with that too.
