### ISSUE TITLE
npm --save install oauth2-implicit downloads 0.6.2 instead 0.7.0

### ISSUE THREAD

**Issue by psumstr** [jasonkuhrt/oauth2-implicit#24]
Not sure if it's because of the extra -0 in 0.7.0-0. I had to manually selected with npm --save install oauth2-implicit@0.7.0-0

**Comment by jasonkuhrt** [comment]
Hey @psumstr. Thanks, I'll look into this soon.

**Comment by jasonkuhrt** [comment]
Pardon the delay, I've been very sick for the past week. This is fixed now! Thanks for reporting.
